name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]
  gollum:

env:
  GIT_AUTHOR_NAME: Actionbot
  GIT_AUTHOR_EMAIL: actions@github.com

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@v1.0.1
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.WIKI_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          commitMessage: "chore(wiki-sync): sync docs changes to wiki

  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WIKI_TOKEN }} # allows us to push back to repo
          ref: master
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@v1.0.1
        with:
          source: wiki
          destination: docs
          token: ${{ secrets.WIKI_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: master
          commitMessage: "chore(wiki-sync): sync wiki changes to docs"